# Generated by Django 2.1.2 on 2018-12-03 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_auto_20181008_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
    ]
