# Generated by Django 2.1.1 on 2018-10-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='ganancia',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='valor_compra',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='valor_venta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
