# Generated by Django 2.1.1 on 2018-10-08 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_auto_20181008_1619'),
        ('Inventario', '0002_auto_20181008_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='empresa',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Empresa.Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Productos.Producto'),
        ),
    ]
